create table PROJECT
(
	ID BIGINT identity (1,1) PRIMARY KEY ,
    IDENTIFIER VARCHAR (30) UNIQUE ,
    NAME VARCHAR (30),
    BUILD_JOB VARCHAR (50),
    DEPLOY_JOB VARCHAR (50),
    DESCRIPTION VARCHAR (100)
);

