create table APPLICATION
(
	ID SERIAL PRIMARY KEY ,
    IDENTIFIER VARCHAR (30) UNIQUE ,
    NAME VARCHAR (30),
    BUILD_JOB VARCHAR (50),
    DEPLOY_JOB VARCHAR (50),
    DESCRIPTION VARCHAR (100)
);

INSERT INTO APPLICATION (id, IDENTIFIER, NAME, DESCRIPTION)
VALUES (DEFAULT, 'dmp', 'dmp-Fachanwendung', 'DMP');