create table APP
(
    ID             SERIAL PRIMARY KEY,
    HOST_ID        INTEGER REFERENCES HOST (ID),
    IMAGE_ID       INTEGER REFERENCES IMAGE (ID),
    APPLICATION_ID INTEGER REFERENCES APPLICATION (ID),
    PORT           VARCHAR(6),
    IMAGE          VARCHAR(100)
);